plugin:
    has_options: false
    icon: res_exo.png
    resources:
        - class: UJM\ExoBundle\Entity\Exercise
          name: ujm_exercise
          is_browsable: false
          icon: res_exo.png
          activity_rules:
            - action: resource-ujm_exercise-exercise_evaluated
        - class: UJM\ExoBundle\Entity\Sequence\Sequence
          name: ujm_sequence
          is_exportable: false
          icon: res_exo.png
          actions:
            - name: administrate
              menu_name: ujm_sequence_administrate
          

    tools:
        - name: ujm_questions
          is_displayable_in_workspace: false
          is_displayable_in_desktop: true
          class: question-circle
