services:    
    # ExercisePlayer type
    ujm_exo_bundle.form.type.exercise_player_type:
        class:  %ujm_exo_bundle.form.type.exercise_player_type.class%
        tags:
          - { name: form.type, alias: exercise_player_type }
