# This file contains the core container parameters. Most of them may be overwritten
# in test environment (see app/config/config_test.yml)

parameters:
    ujm.param.exo_directory: "%claroline.param.uploads_directory%/ujmexo"
    ujm.param.qti_directory: "%ujm.param.exo_directory%/qti"
    
    # Form Types
    ujm_exo_bundle.form.type.sequence_type.class:   UJM\ExoBundle\Form\Sequence\SequenceType
    
    # Managers
    ujm_exo_bundle.manager.sequence.class:    UJM\ExoBundle\Manager\Sequence\SequenceManager
    ujm_exo_bundle.manager.steps.class:    UJM\ExoBundle\Manager\Sequence\StepManager
