# This file contains the core container parameters. Most of them may be overwritten
# in test environment (see app/config/config_test.yml)

parameters:
    ujm.param.exo_directory: "%claroline.param.uploads_directory%/ujmexo"
    ujm.param.qti_directory: "%ujm.param.exo_directory%/qti"
    
    # Form Types
    ujm_exo_bundle.form.type.exercise_player_type.class:   UJM\ExoBundle\Form\Player\ExercisePlayerType
    
    # Managers
    ujm_exo_bundle.manager.exercise_player.class:    UJM\ExoBundle\Manager\Player\ExercisePlayerManager
    ujm_exo_bundle.manager.pages.class:    UJM\ExoBundle\Manager\Player\PageManager
